---
# Generated by tfplugindocs from templates/guides/version-1-upgrade.md.tmpl.
# Edit the template, then run go generate.
page_title: "Upgrading to version 1.0 of the Permit.io provider"
subcategory: ""
description: |-
  What changes between 0.0.x and 1.0 of the permitio/permit-io provider, who each change affects, what to do and what the plan shows.
---

# Upgrading to version 1.0

Version 1.0 of the `permitio/permit-io` provider follows the 0.0.x releases. It fixes bugs, checks more of the configuration at plan time, and declares the Terraform, OpenTofu and operating system versions it supports.

Most configurations upgrade with an empty plan. The provider's upgrade test applies 26 objects, of all 14 resource types, with 0.0.25, then plans the same configuration with 1.0 and expects no changes. The entries below cover the configurations that do change. Read the entries for the arguments you use.

Each entry has an ID, such as `S4`, that stays the same across versions of this guide. Each says what changed, who is affected, what to do, and the plan impact. Entries marked **Bug fix: this could never work** describe behaviour that always failed in 0.0.x, so no working configuration relied on it.

## Plan impact

- **None**: the plan doesn't change.
- **In-place update** (`~`): Terraform updates the object in Permit.
- **Create** (`+`): Terraform creates an object that is missing from Permit.
- **Replacement** (`-/+`): Terraform deletes the object in Permit and creates it again. Permit also deletes what depends on the object, such as role assignments, derived roles and condition set rules. Users can lose access until the apply creates everything again. Replacing a `permitio_resource` or a `permitio_role` can remove access for many users at once. Read every replacement in the plan before you apply it.
- **Plan error**: the plan fails until you change the configuration or the state.

## Upgrade steps

1. Check the compatibility entries: Terraform 1.5.7 or later, or OpenTofu 1.11 or later ([C1](#c1-terraform-157-or-later), [C2](#c2-opentofu-111-or-later)), and macOS 12 or later on a Mac ([C3](#c3-macos-12-or-later-and-the-published-platforms)).
2. Change the version constraint to `~> 1.0` ([P1](#p1-the-version-constraint-selects-10)) and run `terraform init -upgrade`.
3. Fix everything that fails the plan in 1.0. These entries have the plan impact **Plan error**:
   - `resource` on `permitio_user_set` ([S4](#s4-permitio_user_setresource-is-removed)) and any `updated_at` ([S5](#s5-updated_at-is-read-only)): remove them.
   - Outputs that reference `auth_secret` ([S6](#s6-permitio_proxy_configauth_secret-is-sensitive)): mark them sensitive.
   - `auth_mechanism = "Headers"` ([S7](#s7-headers-proxy-authentication-is-rejected)), and mapping rules that repeat a `url` and `http_method` ([S8](#s8-mapping-rules-with-the-same-url-and-http_method-are-rejected)).
   - A user set or resource set that has a parent in Permit and no `parent_id` in the configuration ([S10](#s10-removing-parent_id-fails-at-plan-time)).
   - A `timeout` of 0 or less, or an `api_url` that isn't an absolute `http` or `https` URL ([S11](#s11-the-provider-checks-api_url-and-timeout)).
   - A condition set held in the state under the other type ([ST4](#st4-a-condition-set-of-the-other-type-is-refused)).
   - Placeholder values in the provider block ([B4](#b4-the-provider-block-overrides-environment-variables)), and runs without a valid API key ([B3](#b3-the-provider-checks-the-api-key-on-every-run)).
4. Run `terraform plan`. Compare every change with the plan impact of its entry below. Stop at any replacement (`-/+`) you didn't expect.
5. Apply. If the state has user sets, run `terraform apply -refresh-only` too, so the state no longer holds their removed `resource` ([S4](#s4-permitio_user_setresource-is-removed)).

## Summary

| ID | Change | Plan impact |
|----|--------|-------------|
| [P1](#p1-the-version-constraint-selects-10) | The version constraint selects 1.0 | None |
| [C1](#c1-terraform-157-or-later) | Terraform 1.5.7 or later | None |
| [C2](#c2-opentofu-111-or-later) | OpenTofu 1.11 or later | None |
| [C3](#c3-macos-12-or-later-and-the-published-platforms) | macOS 12 or later; the published platforms | None |
| [S1](#s1-changing-key-replaces-the-object) | Changing `key` replaces the object | Replacement, when a key changes |
| [S2](#s2-changing-a-relations-name-or-description-replaces-it) | Changing a relation's `name` or `description` replaces it | Replacement, when they change |
| [S3](#s3-changing-permitio_resource_setresource-to-another-resource-replaces-the-set) | Changing a resource set's `resource` to another resource replaces the set | Replacement, when it changes |
| [S4](#s4-permitio_user_setresource-is-removed) | `permitio_user_set.resource` is removed | Plan error until removed |
| [S5](#s5-updated_at-is-read-only) | `updated_at` is read-only | Plan error until removed |
| [S6](#s6-permitio_proxy_configauth_secret-is-sensitive) | `permitio_proxy_config.auth_secret` is sensitive | Plan error for outputs that aren't sensitive |
| [S7](#s7-headers-proxy-authentication-is-rejected) | `auth_mechanism = "Headers"` is rejected | Plan error |
| [S8](#s8-mapping-rules-with-the-same-url-and-http_method-are-rejected) | Mapping rules with the same `url` and `http_method` are rejected | Plan error |
| [S9](#s9-removing-a-condition-set-description-clears-it) | Removing a user set or resource set `description` clears it | In-place update |
| [S10](#s10-removing-parent_id-fails-at-plan-time) | Removing `parent_id` fails at plan time | Plan error |
| [S11](#s11-the-provider-checks-api_url-and-timeout) | The provider checks `api_url` and `timeout` | Plan error for invalid values |
| [S12](#s12-data-sources-require-only-their-key) | Data sources require only their key; the condition set data source works | None |
| [S13](#s13-permitio_user_attributedescription-is-optional) | `permitio_user_attribute.description` is optional | None |
| [S14](#s14-mapping-rules-can-match-a-regular-expression) | Mapping rules can match a regular expression (`url_type`) | None |
| [ST1](#st1-import-works-on-every-resource) | Import works on every resource | None |
| [ST2](#st2-composite-import-ids-are-checked) | Composite import IDs are checked | Import error for a malformed ID |
| [ST3](#st3-one-in-place-update-after-importing-with-empty-attributes) | One in-place update after importing with empty `attributes` | In-place update, once |
| [ST4](#st4-a-condition-set-of-the-other-type-is-refused) | A condition set of the other type is refused | Plan error |
| [B1](#b1-objects-deleted-outside-terraform-are-created-again) | Objects deleted outside Terraform are created again | Create |
| [B2](#b2-requests-are-retried-and-timeout-covers-the-retries) | Requests are retried, and `timeout` covers the retries | None |
| [B3](#b3-the-provider-checks-the-api-key-on-every-run) | The provider checks the API key on every run | Plan error for a bad key |
| [B4](#b4-the-provider-block-overrides-environment-variables) | The provider block overrides environment variables | None |
| [B5](#b5-permitio_debug-is-no-longer-read) | `PERMITIO_DEBUG` is no longer read | None |
| [B6](#b6-errors-show-the-http-status-and-the-apis-message) | Errors show the HTTP status and the API's message | None |
| [B7](#b7-role-assignment-reads-find-every-assignment) | Role assignment reads find every assignment | None, or Create |
| [B8](#b8-the-group-role-assignment-uses-the-providers-configuration) | The group role assignment uses the provider's configuration | None |
| [B9](#b9-json-arguments-compare-as-json) | JSON arguments compare as JSON | None, or one in-place update |
| [B10](#b10-removing-tenant-or-resource-instance-attributes-clears-them) | Removing tenant or resource instance `attributes` clears them | In-place update |
| [B11](#b11-descriptions-left-out-of-the-configuration-are-kept) | Descriptions left out of the configuration are kept | None |
| [B12](#b12-removing-a-resources-attributes-clears-them) | Removing a resource's `attributes` clears them | In-place update |
| [B13](#b13-proxy-mapping-rules-match-the-configuration-after-every-apply) | Proxy mapping rules match the configuration after every apply | In-place update |
| [B14](#b14-role-derivation-role-and-to_role) | Role derivation `role` and `to_role` | Replacement, if you swap them |
| [D](#d-deprecations) | Deprecations | None in 1.0 |
| [K1](#k1-object-and-object_array-attribute-types) to [K6](#k6-name-other-objects-by-key) | Known issues | |
| [KP1](#kp1-role-permissions-and-extends) to [KP3](#kp3-the-provider-name-permitio-and-the-registry-name-permit-io) | Kept on purpose | |
| [L1](#l1-staying-on-00x) | Staying on 0.0.x | |

## P: Provider version

### P1. The version constraint selects 1.0

**What changed.** The version is now 1.0.0. The constraint the README used to recommend, `~> 0.0.1`, allows only 0.0.x versions, so it never selects 1.0.

**Who is affected.** Every configuration with a `~> 0.0.x` constraint. A configuration with no constraint, or with one such as `>= 0.0.1`, gets 1.0 on its next `terraform init -upgrade`, or on an `init` without a lock file; read this guide before that happens, or pin 0.0.x ([L1](#l1-staying-on-00x)).

**What to do.** Read this guide first. Then change the constraint and run `terraform init -upgrade`, which also updates `.terraform.lock.hcl`.

Before (0.0.x):

```terraform
terraform {
  required_providers {
    permitio = {
      source  = "permitio/permit-io"
      version = "~> 0.0.1"
    }
  }
}
```

After (1.0):

```terraform
terraform {
  required_providers {
    permitio = {
      source  = "permitio/permit-io"
      version = "~> 1.0"
    }
  }
}
```

**Plan impact:** None. The other entries say what the first plan with 1.0 can show.

## C: Compatibility

### C1. Terraform 1.5.7 or later

**What changed.** 1.0 supports Terraform 1.5.7 or later. The README used to say Terraform 1.0 or later. The offline tests, against a mock of the Permit API, run on Terraform 1.5.7 and 1.16.

**Who is affected.** Anyone who runs Terraform older than 1.5.7 with this provider.

**What to do.** Upgrade Terraform to 1.5.7 or later. Optionally, state the floor in the configuration so an older Terraform stops with a clear message:

```terraform
terraform {
  required_version = ">= 1.5.7"
}
```

**Plan impact:** None.

### C2. OpenTofu 1.11 or later

**What changed.** 1.0 declares support for OpenTofu 1.11 or later. The offline tests run on OpenTofu 1.11 and 1.12.

**Who is affected.** OpenTofu users. 0.0.x declared no OpenTofu support.

**What to do.** Use OpenTofu 1.11 or later. The provider source stays `permitio/permit-io`.

**Plan impact:** None.

### C3. macOS 12 or later, and the published platforms

**What changed.** The provider is built with Go 1.26, and Go 1.26 programs need macOS 12 (Monterey) or later. 0.0.25 was built with Go 1.24 and also ran on macOS 11. Also in 0.0.26.

The published platforms are the same as in 0.0.x: `darwin_amd64`, `darwin_arm64`, `freebsd_386`, `freebsd_amd64`, `freebsd_arm`, `freebsd_arm64`, `linux_386`, `linux_amd64`, `linux_arm`, `linux_arm64`, `windows_386`, `windows_amd64` and `windows_arm64`. The offline tests run on `linux_amd64`, `darwin_arm64` and `windows_amd64`; the other platforms are cross-compiled and not tested.

**Who is affected.** Anyone who runs Terraform on macOS 11 or earlier.

**What to do.** Upgrade macOS, or run Terraform on another machine, such as a Linux CI runner. To stay on macOS 11, pin version `0.0.25` ([L1](#l1-staying-on-00x)).

**Plan impact:** None.

## S: Schema

### S1. Changing `key` replaces the object

**Bug fix: this could never work.**

**What changed.** Changing `key` on `permitio_resource`, `permitio_user_set`, `permitio_resource_set`, `permitio_proxy_config` or `permitio_user_attribute` now plans a replacement. In 0.0.x, the update went to the new key's URL, which doesn't exist, or the API kept the old key, and the apply failed.

**Who is affected.** Configurations that change one of these keys. If an earlier apply of a key change failed with 0.0.x, the configuration still differs from the state, so the first plan with 1.0 replaces the object.

**What to do.** Change a key only when you mean to delete the object and create a new one. Permit deletes the old object, and with it whatever depends on it there, such as role assignments, derived roles and condition set rules.

Terraform replaces a dependent only when the dependent's own arguments change. A dependent that names the replaced object, or an object in between, by a key that didn't change stays in Terraform's state while Permit has deleted it. Either run a second apply, which finds it missing and creates it again ([B1](#b1-objects-deleted-outside-terraform-are-created-again)), or replace it in the same apply with `replace_triggered_by`:

```terraform
resource "permitio_resource_set" "drafts" {
  key      = "drafts"
  name     = "Drafts"
  resource = "document"
  conditions = jsonencode({
    allOf = [{ allOf = [{ "resource.status" = { equals = "draft" } }] }]
  })
}

resource "permitio_condition_set_rule" "reviewers_read_drafts" {
  user_set     = "reviewers"
  permission   = "document:read"
  resource_set = permitio_resource_set.drafts.key

  # Permit deletes this rule when it deletes the resource set. The set's ID
  # changes only when Terraform replaces the set, so the rule is replaced with it.
  lifecycle {
    replace_triggered_by = [permitio_resource_set.drafts.id]
  }
}
```

**Plan impact:** Replacement, when a key changes. None otherwise.

### S2. Changing a relation's `name` or `description` replaces it

**Bug fix: this could never work.**

**What changed.** Changing `name` or `description` on `permitio_relation` now plans a replacement. The API has no update for a relation, so in 0.0.x the apply always failed.

**Who is affected.** Configurations that change a relation's name or description, including any whose earlier apply of such a change failed.

**What to do.** Change them only when you mean to replace the relation. Permit deletes what depends on the relation, such as role derivations that it links. Use `replace_triggered_by` on those dependents, or run a second apply, as in [S1](#s1-changing-key-replaces-the-object).

**Plan impact:** Replacement, when the name or description changes.

### S3. Changing `permitio_resource_set.resource` to another resource replaces the set

**Bug fix: this could never work.**

**What changed.** Changing `resource` on `permitio_resource_set` to another resource now plans a replacement. In 0.0.x, the change showed on every plan and was never applied. Switching between the key and the ID of the same resource doesn't replace the set.

**Who is affected.** Configurations that change a resource set's `resource`. A configuration that showed this change on every plan with 0.0.x gets the replacement on its first plan with 1.0.

**What to do.** Permit deletes the condition set rules on the old set. Replace them in the same apply with `replace_triggered_by`, as in [S1](#s1-changing-key-replaces-the-object), or run a second apply.

**Plan impact:** Replacement, when `resource` names another resource. In-place update, when it switches between the key and the ID of the same resource.

### S4. `permitio_user_set.resource` is removed

**Bug fix: this could never work.**

**What changed.** `resource` is removed from `permitio_user_set`. The API drops it, so it never had an effect, and it showed a change on every plan. It stays on `permitio_resource_set`. It is removed now rather than deprecated, because it never worked.

**Who is affected.** User sets that set `resource`, and states that 0.0.x wrote for user sets.

**What to do.** Delete `resource` from every `permitio_user_set`. Then run `terraform apply -refresh-only` and approve it, even if no user set had `resource`. Until an apply writes the state again, `terraform show -json` and `terraform state show` fail on user sets that 0.0.x wrote to the state, with `unsupported attribute "resource"`.

Before (0.0.x):

```terraform
resource "permitio_user_set" "reviewers" {
  key      = "reviewers"
  name     = "Reviewers"
  resource = "document"
  conditions = jsonencode({
    allOf = [{ allOf = [{ "subject.team" = { equals = "review" } }] }]
  })
}
```

After (1.0):

```terraform
resource "permitio_user_set" "reviewers" {
  key  = "reviewers"
  name = "Reviewers"
  conditions = jsonencode({
    allOf = [{ allOf = [{ "subject.team" = { equals = "review" } }] }]
  })
}
```

**Plan impact:** Plan error (`An argument named "resource" is not expected here`) until you remove it. None after that.

### S5. `updated_at` is read-only

**Bug fix: this could never work.**

**What changed.** `updated_at` is read-only on every resource that has it, and on the `permitio_resource` and `permitio_role` data sources. In 0.0.x, setting it failed after apply.

**Who is affected.** Configurations that set `updated_at`.

**What to do.** Remove `updated_at` from the configuration.

Before (0.0.x):

```terraform
resource "permitio_tenant" "acme" {
  key        = "acme"
  name       = "Acme"
  updated_at = "2025-01-01T00:00:00Z"
}
```

After (1.0):

```terraform
resource "permitio_tenant" "acme" {
  key  = "acme"
  name = "Acme"
}
```

**Plan impact:** Plan error (`Invalid Configuration for Read-Only Attribute`) until you remove it.

### S6. `permitio_proxy_config.auth_secret` is sensitive

**What changed.** The whole `auth_secret` object of `permitio_proxy_config` is sensitive. Plans show `(sensitive value)` instead of the secret. `auth_mechanism` stays visible.

**Who is affected.** Outputs that reference `auth_secret` or a value in it.

**What to do.** Mark those outputs `sensitive = true`. In 0.0.x, the same output worked without it. Terraform still stores the secret in plain text in the state, so take it from a variable marked `sensitive = true` rather than writing it in the configuration.

After (1.0):

```terraform
variable "billing_api_token" {
  type      = string
  sensitive = true
}

resource "permitio_proxy_config" "billing" {
  key            = "billing"
  name           = "Billing API"
  auth_mechanism = "Bearer"
  auth_secret = {
    bearer = var.billing_api_token
  }
  mapping_rules = [
    {
      url         = "https://billing.example.com/v1/invoices"
      http_method = "get"
      resource    = "invoice"
      action      = "read"
    },
  ]
}

output "billing_secret" {
  value     = permitio_proxy_config.billing.auth_secret
  sensitive = true
}
```

**Plan impact:** Plan error (`Output refers to sensitive values`) for such an output until you mark it sensitive. None for the proxy config.

### S7. Headers proxy authentication is rejected

**Bug fix: this could never work.**

**What changed.** `auth_mechanism = "Headers"` on `permitio_proxy_config` fails at plan time. The Go SDK the provider uses sends the secret as a string, and the API wants an object for Headers authentication, so it never worked. `auth_secret.headers` stays in the schema.

**Who is affected.** Configurations that set `auth_mechanism = "Headers"`.

**What to do.** Use `Bearer` or `Basic`, or manage the proxy config outside Terraform until the provider supports Headers ([K2](#k2-headers-proxy-authentication)).

**Plan impact:** Plan error (`Headers authentication is not supported yet; use Bearer or Basic`).

### S8. Mapping rules with the same `url` and `http_method` are rejected

**What changed.** Two `mapping_rules` of one `permitio_proxy_config` with the same `url` and `http_method` fail at plan time. Permit identifies a rule by that pair, and the API collapsed such rules on update.

**Who is affected.** Proxy configs whose `mapping_rules` repeat a `url` and `http_method` pair.

**What to do.** Keep one rule for each pair.

Before (0.0.x):

```terraform
resource "permitio_proxy_config" "reports" {
  key            = "reports"
  name           = "Reports API"
  auth_mechanism = "Bearer"
  auth_secret = {
    bearer = var.reports_api_token
  }
  mapping_rules = [
    {
      url         = "https://reports.example.com/documents"
      http_method = "get"
      resource    = "document"
      action      = "read"
    },
    {
      url         = "https://reports.example.com/documents"
      http_method = "get"
      resource    = "document"
      action      = "list"
    },
  ]
}

variable "reports_api_token" {
  type      = string
  sensitive = true
}
```

After (1.0):

```terraform
resource "permitio_proxy_config" "reports" {
  key            = "reports"
  name           = "Reports API"
  auth_mechanism = "Bearer"
  auth_secret = {
    bearer = var.reports_api_token
  }
  mapping_rules = [
    {
      url         = "https://reports.example.com/documents"
      http_method = "get"
      resource    = "document"
      action      = "read"
    },
  ]
}

variable "reports_api_token" {
  type      = string
  sensitive = true
}
```

**Plan impact:** Plan error (`has the same url ... and http_method ... as mapping_rules[0]`) until the pairs are unique.

### S9. Removing a condition set description clears it

**What changed.** `description` on `permitio_user_set` and `permitio_resource_set` is no longer computed. Removing it from the configuration clears it in Permit, and `description = ""` stays `""`. In 0.0.x, removing it kept the old description in Permit and in the state.

**Who is affected.** User sets and resource sets whose configuration has no `description` while Permit has one, including a description set in the Permit UI.

**What to do.** To keep such a description, add it to the configuration.

**Plan impact:** In-place update that clears the description, for each such set.

### S10. Removing `parent_id` fails at plan time

**Bug fix: removing it never detached the set.**

**What changed.** `parent_id` on `permitio_user_set` and `permitio_resource_set` is no longer computed. A plan that removes it from a set that has a parent fails. The API detaches a set from its parent only on an explicit null, which the Go SDK the provider uses can't send ([K4](#k4-removing-a-parent-from-a-condition-set)). In 0.0.x, removing `parent_id` changed nothing, and the set kept its parent.

**Who is affected.** Sets whose configuration has no `parent_id` while the set has a parent in Permit, including a parent set outside Terraform.

**What to do.** Choose one:

- Keep `parent_id` in the configuration.
- Detach the set outside Terraform, then remove `parent_id`.
- Replace the set: run `terraform taint` on it, then apply. Permit deletes the set's condition set rules with the set; run a second apply to create them again, or use `replace_triggered_by` as in [S1](#s1-changing-key-replaces-the-object). `terraform apply -replace` doesn't help: its plan still starts from the set with the parent and fails with the same error.

```shell
terraform taint permitio_user_set.interns
terraform apply
```

**Plan impact:** Plan error (`Cannot remove the parent of a condition set`) until you do one of these. Replacement, if you taint the set.

### S11. The provider checks `api_url` and `timeout`

**What changed.** In the provider block, `api_url` must be an absolute `http` or `https` URL, and `timeout` must be from 1 to 9223372036 seconds. The provider applies the same checks to `PERMITIO_API_URL` and `PERMITIO_TIMEOUT`. In 0.0.x, a `timeout` of 0 or less meant no time limit. An unknown `timeout`, such as one computed from a resource in the same apply, is now an error, as an unknown `api_key` or `api_url` already was.

**Who is affected.** Configurations and environments that set `timeout` to 0 or less, or `api_url` to a relative URL or another scheme.

**What to do.** Set a positive timeout. It covers each request with its retries ([B2](#b2-requests-are-retried-and-timeout-covers-the-retries)).

Before (0.0.x):

```terraform
provider "permitio" {
  timeout = 0
}
```

After (1.0):

```terraform
provider "permitio" {
  timeout = 300
}
```

**Plan impact:** Plan error for an invalid value in the provider block, and an error when the provider starts for an invalid environment variable.

### S12. Data sources require only their key

**Bug fix, for the condition set data source: this could never work.**

**What changed.** Data sources no longer require arguments they never used: `name` and `actions` on `permitio_resource`, `name` on `permitio_role`, and `name`, `type` and `conditions` on `permitio_condition_set`. They are now optional, and the data source fills them from Permit. The `permitio_condition_set` data source failed on every read in 0.0.x; it now works, fills its optional `resource` from Permit too, and also exports `parent_id`. The `permitio_resource` data source accepts attribute types that aren't known until apply, so it can read a resource created in the same apply.

**Who is affected.** Nobody needs to change anything. Configurations that still set these arguments keep working.

**What to do.** Optionally, remove the arguments you only set because they were required.

Before (0.0.x):

```terraform
data "permitio_role" "admin" {
  key  = "admin"
  name = "Admin"
}
```

After (1.0):

```terraform
data "permitio_role" "admin" {
  key = "admin"
}
```

**Plan impact:** None.

### S13. `permitio_user_attribute.description` is optional

**What changed.** `description` on `permitio_user_attribute` is optional. Leaving it out keeps the description in Permit; `description = ""` clears it.

**Who is affected.** Nobody needs to change anything.

**What to do.** Nothing.

**Plan impact:** None.

### S14. Mapping rules can match a regular expression

**What changed.** Each `mapping_rules` entry of `permitio_proxy_config` has an optional `url_type`. Set it to `regex` to match `url` as a regular expression.

**Who is affected.** Nobody needs to change anything. This is new.

**What to do.** Nothing. See [K5](#k5-a-url-placeholder-in-a-mapping-rule-adds-a-resource-attribute) for why a regular expression can be better than a URL placeholder.

**Plan impact:** None.

## ST: State and import

### ST1. Import works on every resource

**What changed.** Every resource supports import. The eight that had none in 0.0.x import by key, except the relation and the role derivation. Each resource's page shows its import ID:

| Resource | Import ID | New in 1.0 |
|----------|-----------|------------|
| `permitio_resource` | `key` | yes |
| `permitio_user_set` | `key` | yes |
| `permitio_resource_set` | `key` | yes |
| `permitio_proxy_config` | `key` | yes |
| `permitio_tenant` | `key` | yes |
| `permitio_user_attribute` | `key` | yes |
| `permitio_relation` | `object_resource:key` | yes |
| `permitio_role_derivation` | `resource:to_role:on_resource:role:linked_by` | yes |
| `permitio_role` | `role_key`, or `resource_key:role_key` for a resource role | no |
| `permitio_resource_instance` | `resource_key:instance_key` | no |
| `permitio_condition_set_rule` | `user_set,permission,resource_set` | no |
| `permitio_role_assignment` | `user:role:tenant` | no |
| `permitio_resource_instance_role_assignment` | `user:role:resource:resource_instance:tenant` | no |
| `permitio_group_resource_instance_role_assignment` | `group:role:resource:resource_instance:tenant` | no |

Where the whole ID is a key, a key that contains `:` works. In `object_resource:key`, `object_resource` is the resource's key. In a role derivation ID, write the resource part as the configuration does: its ID if the configuration uses the ID, and its key otherwise; if they differ, the next plan replaces the derivation. A proxy config import reads the secret back from Permit.

**Who is affected.** Anyone who wants to bring objects created outside Terraform, or left in Permit by a failed apply, under Terraform.

**What to do.** Use `terraform import`, or an `import` block:

```terraform
import {
  to = permitio_resource.document
  id = "document"
}

resource "permitio_resource" "document" {
  key  = "document"
  name = "Document"
  actions = {
    read = { name = "Read" }
  }
}
```

**Plan impact:** None for objects already in the state.

### ST2. Composite import IDs are checked

**What changed.** The import IDs of `permitio_relation`, `permitio_role_derivation`, `permitio_role_assignment`, `permitio_resource_instance_role_assignment` and `permitio_group_resource_instance_role_assignment` are split on `:`. Each must have the expected number of parts, none of them empty, or the import fails with `Invalid import ID` and the expected format. In 0.0.x, the assignment resources sent an ID with an empty part to the API.

`permitio_role`, `permitio_resource_instance` and `permitio_condition_set_rule` parse their IDs as in 0.0.x, and fail with `Invalid Import ID Format`. A role ID is `role_key` or `resource_key:role_key`. A resource instance ID is split at its first `:`, so the instance key may contain `:`. A condition set rule ID is split on `,`, because its permission, such as `document:read`, contains `:`.

**Who is affected.** Imports with a malformed ID, such as `alice::default`. An object can't be imported when a key that contains `:` is one part of an ID split on `:`, except the instance key of a resource instance.

**What to do.** Use the format in [ST1](#st1-import-works-on-every-resource).

**Plan impact:** None. A malformed ID fails the import.

### ST3. One in-place update after importing with empty `attributes`

**What changed.** An object imported without attributes has none in the state. If the configuration sets them explicitly empty, `attributes = {}` on `permitio_resource` or `attributes = jsonencode({})` on `permitio_tenant` or `permitio_resource_instance`, the first plan after the import adds them.

**Who is affected.** Configurations that import such objects and set empty attributes.

**What to do.** Apply the plan, which changes nothing in Permit, or leave `attributes` out.

**Plan impact:** In-place update, once, with no change in Permit.

### ST4. A condition set of the other type is refused

**What changed.** A `permitio_user_set` whose key belongs to a resource set in Permit, or a `permitio_resource_set` whose key belongs to a user set, fails to read with `Condition set of another type`. In 0.0.x, it adopted the other set.

**Who is affected.** States that hold a condition set under the wrong resource type, for example after an import of the wrong type.

**What to do.** Remove it from the state and import it as the right type. With any supported version, run `terraform state rm` on the address, then `terraform import` with the right type. With Terraform 1.7 or later, or OpenTofu, you can do both in the configuration:

```terraform
removed {
  from = permitio_user_set.drafts

  lifecycle {
    destroy = false
  }
}

import {
  to = permitio_resource_set.drafts
  id = "drafts"
}

resource "permitio_resource_set" "drafts" {
  key      = "drafts"
  name     = "Drafts"
  resource = "document"
  conditions = jsonencode({
    allOf = [{ allOf = [{ "resource.status" = { equals = "draft" } }] }]
  })
}
```

**Plan impact:** Plan error until the state holds the right type.

## B: Plan and wire behaviour

### B1. Objects deleted outside Terraform are created again

**What changed.** When an object in the state no longer exists in Permit, the refresh removes it from the state, and the plan creates it again. In 0.0.x, every plan failed with `Unable to read ...` for eight of the resource types once the object was deleted in Permit. Destroying an object that is already gone now succeeds for all 14 resource types; in 0.0.x it failed. Only a 404 counts as gone; other errors, such as a 500 or a bad API key, still fail the plan. The role derivation part is also in 0.0.26.

**Who is affected.** Anyone whose objects are deleted outside Terraform, in the Permit UI, through the API, or by Permit when it deletes an object they depend on ([S1](#s1-changing-key-replaces-the-object)).

**What to do.** Read the plan. An object planned for creation that you expected to exist was deleted outside Terraform.

**Plan impact:** Create, for each object deleted outside Terraform. None for objects that exist.

### B2. Requests are retried, and `timeout` covers the retries

**What changed.** The provider retries:

- a 429 response, for every method, after its `Retry-After`;
- a 502, 503 or 504 response, for GET, HEAD, OPTIONS, PUT and DELETE only, so a create (POST) or an update (PATCH) is never sent twice after a 5xx;
- a connection that could not be opened.

It waits from 1 second, doubling up to 16 seconds, for at most 6 attempts, and never past the request's time limit. `timeout` is now the limit for a request together with all its retries; the default is 10 seconds. Requests carry the header `User-Agent: terraform-provider-permitio/<version>`.

**Who is affected.** Large configurations, and runs that hit the API's rate limit, which used to fail on the first 429.

**What to do.** If 429 errors persist, raise `timeout`:

```terraform
provider "permitio" {
  timeout = 60
}
```

**Plan impact:** None.

### B3. The provider checks the API key on every run

**What changed.** When the provider starts, it asks the API once for the key's organization, project and environment. It does this on every run that uses the provider, including `terraform plan -refresh=false` and a plan whose objects are all still to be created. A bad key, or an API it can't reach, fails there with the HTTP status, the API's message and a hint on what to check. In 0.0.x, the failure came on the first request as `ErrorCode: ContextError … invalid -`, and a plan that sent no request, such as one whose objects were all still to be created, succeeded with an invalid key.

**Who is affected.** Pipelines that plan without a valid API key or without network access to the API. `terraform validate` doesn't configure the provider, so it makes no API call and isn't affected.

**What to do.** Give every run that plans or applies a valid environment-level API key and access to the API.

**Plan impact:** None with a valid key. Plan error with an invalid or missing key.

### B4. The provider block overrides environment variables

**What changed.** The provider takes each setting from the provider block first, then from a non-empty environment variable, then from the default. In 0.0.x, `PERMITIO_API_KEY`, `PERMITIO_API_URL` and `PERMITIO_TIMEOUT` overrode the block, even when set to an empty string, and an empty `PERMITIO_API_KEY` sent requests with no key. An empty environment variable now counts as unset. With no API key in the block or in `PERMITIO_API_KEY`, the provider fails before it sends any request.

**Who is affected.** Configurations that set a value in the provider block and rely on its environment variable to override it. That includes the placeholders from the old README, `api_key = "YOUR_API_KEY"` and `api_url = "https://api.permit.io"`, kept in the block while the real values come from the environment.

**What to do.** Leave an argument out of the provider block to use its environment variable.

Before (0.0.x), with the key in `PERMITIO_API_KEY`:

```terraform
provider "permitio" {
  api_url = "https://api.permit.io"
  api_key = "YOUR_API_KEY"
}
```

After (1.0):

```terraform
provider "permitio" {}
```

**Plan impact:** None for the state. A placeholder key left in the block fails the plan ([B3](#b3-the-provider-checks-the-api-key-on-every-run)).

### B5. `PERMITIO_DEBUG` is no longer read

**What changed.** The provider no longer reads `PERMITIO_DEBUG`. It never had any effect.

**Who is affected.** Nobody. Use `TF_LOG=DEBUG` for the provider's debug logs.

**What to do.** Optionally, remove `PERMITIO_DEBUG` from your environment.

**Plan impact:** None.

### B6. Errors show the HTTP status and the API's message

**What changed.** Every create, read, update and delete error names the operation, the object and its key, the HTTP status, and the API's message. API keys are redacted. Some error summaries that named the wrong object type are corrected. Some configurations that used to crash the provider now get an error instead.

**Who is affected.** Scripts that match on the text of the provider's errors.

**What to do.** Update such scripts.

**Plan impact:** None.

### B7. Role assignment reads find every assignment

**What changed.** The assignment resources read every page of the API's lists:

- `permitio_resource_instance_role_assignment`: an assignment past the first 100 read as deleted in 0.0.x, so every plan created it again.
- `permitio_group_resource_instance_role_assignment`: in a group with more than 30 roles, the other assignments read as deleted in 0.0.25, so every plan created them again. Also in 0.0.26.
- `permitio_role_assignment`: the API's list also holds the user's assignments of a resource role with the same key on resource instances. 0.0.x took the first row, so a tenant-level assignment deleted outside Terraform still read as present while an instance-level one existed. 1.0 skips instance-level rows.

A list error on any page fails the read instead of counting as not found.

**Who is affected.** Users and groups with many assignments, and users with both tenant-level and instance-level assignments of a role with the same key.

**What to do.** Nothing.

**Plan impact:** None for assignments that exist. The create planned on every run for an assignment past the first page stops. Create, for a tenant-level assignment that was deleted outside Terraform and that 0.0.x read as present.

### B8. The group role assignment uses the provider's configuration

**What changed.** `permitio_group_resource_instance_role_assignment` sends its requests through the provider's client, with the provider's API key, URL, timeout and retries. In 0.0.x, it read `PERMITIO_API_KEY` or `PERMIT_API_KEY` itself, could fall back to a fixed URL, and listed tenants to find its environment, so it failed in an environment with no tenants.

**Who is affected.** Configurations that set the API key or URL only in the provider block, set `PERMIT_API_KEY`, or use an environment with no tenants.

**What to do.** Nothing. Nothing reads `PERMIT_API_KEY` any more.

**Plan impact:** None.

### B9. JSON arguments compare as JSON

**Bug fix, for `"{}"` and reordered keys: these could never work.**

**What changed.** `attributes` on `permitio_tenant` and `permitio_resource_instance`, and `conditions` on `permitio_user_set` and `permitio_resource_set`, compare as JSON. Key order, whitespace, heredocs and `"{}"` no longer show a change. Integers above 2^53 keep their digits. In 0.0.x, they compared as text: `"{}"` and reordered keys failed with `inconsistent result after apply`, and heredoc conditions left a change after every apply.

**Who is affected.** Configurations that write these arguments as a heredoc or a JSON string, rather than with `jsonencode`.

**What to do.** Nothing.

**Plan impact:** None for an unchanged configuration that 0.0.x applied without errors. One in-place update that sends the same object, when the configuration's formatting differs from the state, for example when you only reformat the JSON. Terraform requires the plan of an argument that isn't computed to match the configuration exactly.

### B10. Removing tenant or resource instance `attributes` clears them

**Bug fix: removing them never cleared them.**

**What changed.** `attributes` on `permitio_tenant` and `permitio_resource_instance` is no longer computed. Leaving it out means the object has no attributes, so removing it clears them in Permit. In 0.0.x, they stayed in Permit and in the state.

**Who is affected.** Tenants and resource instances whose configuration has no `attributes` while Permit holds attributes, including attributes set outside Terraform.

**What to do.** To keep such attributes, add them to the configuration:

```terraform
resource "permitio_tenant" "acme" {
  key        = "acme"
  name       = "Acme"
  attributes = jsonencode({ tier = "gold" })
}
```

**Plan impact:** In-place update that clears the attributes, for each such object.

### B11. Descriptions left out of the configuration are kept

**What changed.** An unset `description` on `permitio_resource`, `permitio_role`, `permitio_tenant` and `permitio_relation`, and an unset `urn` on `permitio_resource`, are left out of requests. In 0.0.x, they were sent as `""`, which wiped a value set in the Permit UI.

**Who is affected.** Objects whose description or URN is set outside Terraform.

**What to do.** Nothing.

**Plan impact:** None.

### B12. Removing a resource's `attributes` clears them

**Bug fix: this could never work.**

**What changed.** Removing the `attributes` block of a `permitio_resource`, or leaving it out while Permit holds attributes, now clears them in Permit. In 0.0.x, the apply failed with `inconsistent result after apply`, and the attributes stayed in Permit. Removing an attribute also makes Permit delete the resource sets whose conditions reference it.

**Who is affected.** Resources whose configuration has no `attributes`, or fewer attributes than Permit holds, including attributes added outside Terraform or by a proxy mapping rule ([K5](#k5-a-url-placeholder-in-a-mapping-rule-adds-a-resource-attribute)).

**What to do.** Declare every attribute you want to keep in the resource's `attributes`. Check the plan for attributes it removes.

**Plan impact:** In-place update that removes the attributes, and with them the resource sets that reference them.

### B13. Proxy mapping rules match the configuration after every apply

**Bug fix: this could never work.**

**What changed.** An update of `permitio_proxy_config` removes every rule in the state and adds the planned rules, in one request. Removing a rule, or changing its `url` or `http_method`, now removes the old rule in Permit. In 0.0.x, the old rule stayed and the apply failed. After every apply, Permit holds exactly the configured rules in the configured order.

**Who is affected.** Proxy configs whose rules change, and proxy configs with rules added outside Terraform: the next apply removes them.

**What to do.** Keep every rule you need in the configuration.

**Plan impact:** In-place update, when Permit holds rules that the configuration doesn't. Terraform doesn't detect rules reordered outside Terraform; the next update of the proxy config restores the configured order.

### B14. Role derivation `role` and `to_role`

**What changed.** The provider's handling of `permitio_role_derivation` didn't change, but the 0.0.25 docs and example put each role on the wrong resource. Users who have `role` on an `on_resource` instance get `to_role` on the `resource` instances linked to it by `linked_by`. When `role` and `to_role` don't exist on the resources the derivation names, the create error now says what must exist. The corrected docs are also in 0.0.26.

**Who is affected.** Configurations written from the old example or docs. Where the role keys exist on both resources, they create the reverse grant, and still do in 1.0.

**What to do.** Check each derivation, and swap `role` and `to_role` where they are reversed.

Before, from the old example (folder admins meant to get the admin role on each file in the folder):

```terraform
resource "permitio_role_derivation" "folder_file_admin" {
  resource    = "file"
  role        = "fileAdmin"
  on_resource = "folder"
  to_role     = "folderAdmin"
  linked_by   = "parent"
}
```

After:

```terraform
resource "permitio_role_derivation" "folder_file_admin" {
  role        = "folderAdmin"
  on_resource = "folder"
  to_role     = "fileAdmin"
  resource    = "file"
  linked_by   = "parent"
}
```

**Plan impact:** Replacement of the derivation, when you swap them. Every argument of a role derivation forces a replacement.

## D: Deprecations

1.0 deprecates nothing for removal in 2.0. `permitio_user_set.resource` is removed in 1.0 rather than deprecated, because it never had an effect ([S4](#s4-permitio_user_setresource-is-removed)).

## K: Known issues

### K1. `object` and `object_array` attribute types

The provider can't read a resource that has an attribute of type `object` or `object_array`, or a user attribute of either type: the Go SDK the provider uses doesn't know these types (PER-16616). Such an object fails to refresh, whether a resource or a data source reads it. The provider's `type` arguments accept `bool`, `number`, `string`, `time`, `array` and `json`. Manage objects that use these types outside Terraform until this is fixed.

### K2. Headers proxy authentication

`auth_mechanism = "Headers"` fails at plan time ([S7](#s7-headers-proxy-authentication-is-rejected)). The Go SDK sends and reads the proxy secret as a string, and the API wants an object for Headers authentication (PER-16617).

### K3. Clearing some descriptions

Removing the `description` of a `permitio_tenant`, or of an action or attribute of a `permitio_resource`, doesn't clear it in Permit. The Go SDK leaves a missing value out of the request instead of sending a null, and the API keeps the old value. For an action or attribute, the apply can then fail with an inconsistent result. Clear the description in the Permit UI or with the API, then remove it from the configuration.

### K4. Removing a parent from a condition set

The provider can't detach a user set or resource set from its parent in place, because the Go SDK can't send the null the API needs. See [S10](#s10-removing-parent_id-fails-at-plan-time) for what to do.

### K5. A URL placeholder in a mapping rule adds a resource attribute

A mapping rule `url` with a placeholder, such as `{invoice_id}` in `https://billing.example.com/v1/invoices/{invoice_id}`, makes Permit add an attribute of that name to the rule's resource. A `permitio_resource` that manages that resource then plans to remove the attribute ([B12](#b12-removing-a-resources-attributes-clears-them)). Declare the attribute in the resource's `attributes` with the type Permit gives it, or match the URL with a regular expression instead:

```terraform
variable "billing_api_token" {
  type      = string
  sensitive = true
}

resource "permitio_proxy_config" "billing" {
  key            = "billing"
  name           = "Billing API"
  auth_mechanism = "Bearer"
  auth_secret = {
    bearer = var.billing_api_token
  }
  mapping_rules = [
    {
      url         = "^https://billing\\.example\\.com/v1/invoices/[0-9]+$"
      url_type    = "regex"
      http_method = "get"
      resource    = "invoice"
      action      = "read"
    },
  ]
}
```

### K6. Name other objects by key

Arguments that name another object, such as `subject_resource` and `object_resource` on a relation, or the permissions of a role, work reliably only with keys. Permit returns keys, so an ID there never matches what Permit returns: the plan shows a change on every run, or the apply fails with an inconsistent result. 1.0 doesn't check this at plan time. Use keys, such as `permitio_resource.document.key`, rather than IDs.

## KP: Kept on purpose

### KP1. Role `permissions` and `extends`

Leaving `permissions` or `extends` out of a `permitio_role` keeps what the role has in Permit, including permissions granted outside Terraform. So removing either argument from the configuration doesn't remove anything. To remove them all, set the argument to `[]` (PER-16624):

```terraform
resource "permitio_role" "viewer" {
  key         = "viewer"
  name        = "Viewer"
  permissions = []
  extends     = []
}
```

### KP2. `mapping_rules` stays a list

`mapping_rules` on `permitio_proxy_config` stays a list, so its order is part of the configuration: Permit holds the rules in the configured order, and reordering the list plans an in-place update.

### KP3. The provider name `permitio` and the registry name `permit-io`

The registry address stays `permitio/permit-io`, and the provider's type name stays `permitio`, so resources and data sources keep their `permitio_` prefix. Use `permitio` as the local name in `required_providers`, as in [P1](#p1-the-version-constraint-selects-10). No source address or resource address changes in 1.0.

## L: Staying on 0.0.x

### L1. Staying on 0.0.x

To stay on 0.0.x, pin a constraint that excludes 1.0:

```terraform
terraform {
  required_providers {
    permitio = {
      source  = "permitio/permit-io"
      version = "~> 0.0.26"
    }
  }
}
```

`~> 0.0.26` selects 0.0.26 or a later 0.0.x release, never 1.0. 0.0.26 adds these to 0.0.25: fixed dependency vulnerabilities and the Go 1.26 build, which needs macOS 12 ([C3](#c3-macos-12-or-later-and-the-published-platforms)); the corrected role derivation docs and example ([B14](#b14-role-derivation-role-and-to_role)), and a role derivation deleted outside Terraform is created again; and group role assignments past the first page ([B7](#b7-role-assignment-reads-find-every-assignment)). On macOS 11, pin `version = "0.0.25"`.

0.0.x doesn't have the rest of this guide, including:

- recreating other objects deleted outside Terraform, and destroying objects already gone ([B1](#b1-objects-deleted-outside-terraform-are-created-again));
- retries of rate-limited requests ([B2](#b2-requests-are-retried-and-timeout-covers-the-retries));
- import for eight resources ([ST1](#st1-import-works-on-every-resource));
- key, relation and resource set changes that apply ([S1](#s1-changing-key-replaces-the-object) to [S3](#s3-changing-permitio_resource_setresource-to-another-resource-replaces-the-set));
- JSON comparison of attributes and conditions ([B9](#b9-json-arguments-compare-as-json));
- a sensitive proxy secret ([S6](#s6-permitio_proxy_configauth_secret-is-sensitive));
- mapping rules that can be removed or re-keyed ([B13](#b13-proxy-mapping-rules-match-the-configuration-after-every-apply)), and regular-expression URLs ([S14](#s14-mapping-rules-can-match-a-regular-expression));
- the working condition set data source ([S12](#s12-data-sources-require-only-their-key)).
