package mockpermit

import (
	"maps"
	"net/http"
)

const (
	conditionSetCollection = "condition_sets"
	conditionSetsPattern   = "/v2/schema/{proj_id}/{env_id}/condition_sets"
	conditionSetPattern    = conditionSetsPattern + "/{condition_set_id}"
	userSetType            = "userset"
	resourceSetType        = "resourceset"
)

// ConditionSets serves the condition set operations permitio_user_set and
// permitio_resource_set call: create, and get, update and delete by key or ID.
// A resource set's resource_id may name its resource by key or ID; the fake
// stores the ID and returns the resource in the set, as the API does. Names are
// unique in an environment, like keys. A parent_id must be the ID of another set
// of the same type and resource. Whether the API also takes a parent key, a parent
// of another kind, a null parent_id, a user set with a resource_id or a resource
// set on the built-in __user resource is unconfirmed, so the fake fails the test
// on them. It also fails the test on a get, update or delete of a resource set
// whose resource was deleted: the API deletes a resource with its related data,
// and whether that includes the set is unconfirmed. So is what happens to a set
// whose parent is deleted, so the fake fails the test on that delete too.
var ConditionSets = Routes{
	{"POST " + conditionSetsPattern, "ConditionSets.Create", (*Server).createConditionSet},
	{"GET " + conditionSetPattern, "ConditionSets.Get", (*Server).getConditionSet},
	{"PATCH " + conditionSetPattern, "ConditionSets.Update", (*Server).updateConditionSet},
	{"DELETE " + conditionSetPattern, "ConditionSets.Delete", (*Server).deleteConditionSet},
}

func (s *Server) createConditionSet(w http.ResponseWriter, r *http.Request) {
	body, ok := s.decodeObject(w, r)
	if !ok || !s.knownFieldsOnly(w, body, "key", "type", "autogenerated", "resource_id", "name",
		"description", "conditions", "parent_id") {
		return
	}
	key, name, setType := str(body, "key"), str(body, "name"), str(body, "type")
	if _, given := body["type"]; !given {
		setType = userSetType
	}
	if key == "" || name == "" {
		s.writeError(w, http.StatusUnprocessableEntity, "UNPROCESSABLE_ENTITY",
			"key and name are required")
		return
	}
	if setType != userSetType && setType != resourceSetType {
		s.writeError(w, http.StatusUnprocessableEntity, "UNPROCESSABLE_ENTITY",
			"type must be userset or resourceset")
		return
	}
	if !s.objectIfGiven(w, body, "conditions") {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	sets := s.collection(conditionSetCollection)
	if _, exists := sets[key]; exists {
		s.writeError(w, http.StatusConflict, "DUPLICATE_ENTITY",
			"condition set "+key+" already exists")
		return
	}
	if s.conditionSetNamed(name) != nil {
		s.writeError(w, http.StatusConflict, "DUPLICATE_ENTITY",
			"a condition set named "+name+" already exists")
		return
	}
	set := map[string]any{"autogenerated": false, "conditions": map[string]any{}}
	maps.Copy(set, body)
	set["type"] = setType
	switch {
	case setType == resourceSetType:
		if str(body, "resource_id") == "" {
			s.writeError(w, http.StatusUnprocessableEntity, "UNPROCESSABLE_ENTITY",
				"a resource set needs a resource_id")
			return
		}
		resource, ok := s.parentResource(w, str(body, "resource_id"))
		if !ok {
			return
		}
		if resource["id"] == UserResourceID {
			s.refuseUnconfirmed(w, r, "the body puts a resource set on the built-in "+
				userResourceKey+" resource")
			return
		}
		set["resource_id"] = resource["id"]
	case body["resource_id"] != nil:
		s.refuseUnconfirmed(w, r, "the body gives a user set a resource_id")
		return
	}
	if parentID := body["parent_id"]; parentID != nil && !s.setParent(w, r, set, parentID) {
		return
	}
	maps.Copy(set, s.newObject())
	sets[key] = set
	s.writeJSON(w, http.StatusOK, s.conditionSetRead(set))
}

func (s *Server) getConditionSet(w http.ResponseWriter, r *http.Request) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if set, ok := s.pathConditionSet(w, r); ok {
		s.writeJSON(w, http.StatusOK, s.conditionSetRead(set))
	}
}

// updateConditionSet overwrites each field the body provides, as the API documents
// for this PATCH. A refused PATCH leaves the set as it was.
func (s *Server) updateConditionSet(w http.ResponseWriter, r *http.Request) {
	body, ok := s.decodeObject(w, r)
	if !ok || !s.knownFieldsOnly(w, body, "name", "description", "conditions", "parent_id") {
		return
	}
	if _, given := body["name"]; given && str(body, "name") == "" {
		s.writeError(w, http.StatusUnprocessableEntity, "UNPROCESSABLE_ENTITY",
			"name must be a non-empty string")
		return
	}
	if !s.objectIfGiven(w, body, "conditions") {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	set, ok := s.pathConditionSet(w, r)
	if !ok {
		return
	}
	if named := s.conditionSetNamed(str(body, "name")); named != nil && named["id"] != set["id"] {
		s.writeError(w, http.StatusConflict, "DUPLICATE_ENTITY",
			"a condition set named "+str(body, "name")+" already exists")
		return
	}
	updated := maps.Clone(set)
	maps.Copy(updated, body)
	if parentID, given := body["parent_id"]; given && !s.setParent(w, r, updated, parentID) {
		return
	}
	s.collection(conditionSetCollection)[str(set, "key")] = updated
	s.writeJSON(w, http.StatusOK, s.conditionSetRead(updated))
}

// deleteConditionSet deletes a condition set. The API also deletes the rules that
// grant permissions to it or on it; the fake keeps them, so a test that deletes a
// set before its rules sees them in StoredKeys. It fails the test on a delete of
// a set that is the parent of another set: whether the API then deletes the child
// too, clears its parent_id or refuses the delete is unconfirmed.
func (s *Server) deleteConditionSet(w http.ResponseWriter, r *http.Request) {
	s.mu.Lock()
	defer s.mu.Unlock()
	set, ok := s.pathConditionSet(w, r)
	if !ok {
		return
	}
	for _, child := range s.collection(conditionSetCollection) {
		if child["parent_id"] == set["id"] {
			s.refuseUnconfirmed(w, r, "the path names the parent of the condition set "+
				str(child, "key"))
			return
		}
	}
	delete(s.collection(conditionSetCollection), str(set, "key"))
	w.WriteHeader(http.StatusNoContent)
}

// pathConditionSet returns the condition set the request path names. It writes a
// 404 when there is none, and fails the test when it is a resource set whose
// resource was deleted; see ConditionSets. The caller holds s.mu.
func (s *Server) pathConditionSet(w http.ResponseWriter, r *http.Request) (map[string]any, bool) {
	set, ok := s.find(conditionSetCollection, r.PathValue("condition_set_id"))
	if !ok {
		s.writeError(w, http.StatusNotFound, "NOT_FOUND", "condition set not found")
		return nil, false
	}
	if s.resourceDeleted(set) {
		s.refuseUnconfirmed(w, r, "the path names a resource set whose resource was deleted")
		return nil, false
	}
	return set, true
}

// resourceDeleted reports whether an object that belongs to a resource, such as a
// resource set, names by resource_id a resource that no longer exists. The caller
// holds s.mu.
func (s *Server) resourceDeleted(object map[string]any) bool {
	resourceID := str(object, "resource_id")
	if resourceID == "" {
		return false
	}
	_, exists := s.find(resourceCollection, resourceID)
	return !exists
}

// setParent sets the parent_id of set to the ID in value, or writes an error and
// returns false. The parent must be another set of the same type and, for a
// resource set, on the same resource. The caller holds s.mu.
func (s *Server) setParent(w http.ResponseWriter, r *http.Request, set map[string]any,
	value any,
) bool {
	if value == nil {
		s.refuseUnconfirmed(w, r, "the body sets parent_id to null")
		return false
	}
	parentID, ok := value.(string)
	if !ok {
		s.writeError(w, http.StatusUnprocessableEntity, "UNPROCESSABLE_ENTITY",
			"parent_id is not a string")
		return false
	}
	sets := s.collection(conditionSetCollection)
	var parent map[string]any
	for _, candidate := range sets {
		if candidate["id"] == parentID {
			parent = candidate
		}
	}
	switch {
	case parent == nil && sets[parentID] != nil:
		s.refuseUnconfirmed(w, r, "the body names the parent "+parentID+" by key")
		return false
	case parent == nil:
		s.writeError(w, http.StatusNotFound, "NOT_FOUND", "parent condition set not found")
		return false
	case parent["id"] == set["id"] || parent["type"] != set["type"] ||
		parent["resource_id"] != set["resource_id"]:
		s.refuseUnconfirmed(w, r, "parent_id names the set itself, or a set of another type "+
			"or resource")
		return false
	}
	set["parent_id"] = parentID
	return true
}

// conditionSetNamed returns the condition set with this name, or nil. The caller
// holds s.mu.
func (s *Server) conditionSetNamed(name string) map[string]any {
	for _, set := range s.collection(conditionSetCollection) {
		if name != "" && set["name"] == name {
			return set
		}
	}
	return nil
}

// conditionSetRead returns a condition set as the API returns it: a resource set
// has its resource in it. The caller holds s.mu and has checked that a resource
// set's resource exists.
func (s *Server) conditionSetRead(set map[string]any) map[string]any {
	read := maps.Clone(set)
	if resource, ok := s.find(resourceCollection, str(set, "resource_id")); ok {
		read["resource"] = s.resourceRead(resource)
	}
	return read
}
