package mockpermit

import (
	"net/http"
	"reflect"
	"strings"
	"testing"
)

const conditionSetsPath = schemaPath + "/condition_sets"

// wantUnconfirmed fails the test unless the mock failed it exactly once, with an
// error that calls the request unconfirmed and contains want.
func wantUnconfirmed(t *testing.T, rec *errorRecorder, want string) {
	t.Helper()
	got := rec.take()
	if len(got) != 1 || !strings.Contains(got[0], "unconfirmed") ||
		!strings.Contains(got[0], want) {
		t.Errorf("test errors = %q, want one calling %q unconfirmed", got, want)
	}
}

func TestUserSetState(t *testing.T) {
	m := New(t, ConditionSets)

	created := send(t, m, http.MethodPost, conditionSetsPath, `{"key": "staff", "name": "Staff",
		"description": "d", "conditions": {"allOf": [{"subject.a": {"equals": 1}}]}}`,
		http.StatusOK)

	wantSet := `{
		"id": "` + ObjectID(1) + `", "key": "staff", "name": "Staff", "description": "d",
		"type": "userset", "autogenerated": false,
		"conditions": {"allOf": [{"subject.a": {"equals": 1}}]},
		"organization_id": "` + OrganizationID + `", "project_id": "` + ProjectID + `",
		"environment_id": "` + EnvironmentID + `",
		"created_at": "` + timestamp + `", "updated_at": "` + timestamp + `"
	}`
	wantFields(t, created, wantSet)
	for _, field := range []string{"resource", "resource_id", "parent_id"} {
		if _, ok := created[field]; ok {
			t.Errorf("a user set has %s: %v", field, created)
		}
	}
	wantFields(t, send(t, m, http.MethodGet, conditionSetsPath+"/staff", "", http.StatusOK),
		wantSet)
	wantFields(t, send(t, m, http.MethodGet, conditionSetsPath+"/"+ObjectID(1), "",
		http.StatusOK), wantSet)
	send(t, m, http.MethodGet, conditionSetsPath+"/missing", "", http.StatusNotFound)
	send(t, m, http.MethodPost, conditionSetsPath, `{"key": "staff", "name": "Again"}`,
		http.StatusConflict)
	send(t, m, http.MethodPost, conditionSetsPath, `{"key": "other", "name": "Staff"}`,
		http.StatusConflict)
	wantFields(t, send(t, m, http.MethodPost, conditionSetsPath,
		`{"key": "admins", "name": "Admins", "type": "userset"}`, http.StatusOK),
		`{"id": "`+ObjectID(2)+`", "type": "userset", "conditions": {}}`)
	wantStoredKeys(t, m, "condition_sets/admins", "condition_sets/staff")

	updated := send(t, m, http.MethodPatch, conditionSetsPath+"/admins", `{"name": "Admins 2",
		"conditions": {"anyOf": []}, "parent_id": "`+ObjectID(1)+`"}`, http.StatusOK)

	wantUpdated := `{"id": "` + ObjectID(2) + `", "key": "admins", "name": "Admins 2",
		"conditions": {"anyOf": []}, "parent_id": "` + ObjectID(1) + `"}`
	wantFields(t, updated, wantUpdated)
	wantFields(t, send(t, m, http.MethodGet, conditionSetsPath+"/admins", "", http.StatusOK),
		wantUpdated)
	send(t, m, http.MethodPatch, conditionSetsPath+"/admins", `{"name": "Staff"}`,
		http.StatusConflict)
	wantFields(t, send(t, m, http.MethodPatch, conditionSetsPath+"/"+ObjectID(1),
		`{"name": "Staff", "description": "d2"}`, http.StatusOK),
		`{"name": "Staff", "description": "d2", "conditions": {"allOf": [{"subject.a":
			{"equals": 1}}]}}`)
	send(t, m, http.MethodPatch, conditionSetsPath+"/missing", `{"name": "x"}`,
		http.StatusNotFound)

	send(t, m, http.MethodDelete, conditionSetsPath+"/admins", "", http.StatusNoContent)

	wantStoredKeys(t, m, "condition_sets/staff")
	send(t, m, http.MethodGet, conditionSetsPath+"/admins", "", http.StatusNotFound)
	send(t, m, http.MethodDelete, conditionSetsPath+"/admins", "", http.StatusNotFound)
	send(t, m, http.MethodDelete, conditionSetsPath+"/"+ObjectID(1), "", http.StatusNoContent)
	wantStoredKeys(t, m)
}

func TestResourceSetState(t *testing.T) {
	m := New(t, Resources, ConditionSets)
	send(t, m, http.MethodPost, resourcesPath, `{"key": "document", "name": "Document",
		"actions": {"read": {"name": "Read"}}}`, http.StatusOK)

	created := send(t, m, http.MethodPost, conditionSetsPath, `{"key": "drafts",
		"name": "Drafts", "type": "resourceset", "resource_id": "document"}`, http.StatusOK)

	wantSet := `{"id": "` + ObjectID(3) + `", "key": "drafts", "type": "resourceset",
		"resource_id": "` + ObjectID(1) + `", "conditions": {}}`
	wantFields(t, created, wantSet)
	resource, _ := created["resource"].(map[string]any)
	wantFields(t, resource, `{"id": "`+ObjectID(1)+`", "key": "document", "name": "Document",
		"actions": {"read": {"id": "`+ObjectID(2)+`", "key": "read", "name": "Read"}}}`)
	got := send(t, m, http.MethodGet, conditionSetsPath+"/drafts", "", http.StatusOK)
	if !reflect.DeepEqual(got, created) {
		t.Errorf("GET = %v, want the created set %v", got, created)
	}
	byID := send(t, m, http.MethodPost, conditionSetsPath, `{"key": "reviewed",
		"name": "Reviewed", "type": "resourceset", "resource_id": "`+ObjectID(1)+`",
		"parent_id": "`+ObjectID(3)+`"}`, http.StatusOK)
	wantFields(t, byID, `{"resource_id": "`+ObjectID(1)+`", "parent_id": "`+ObjectID(3)+`"}`)
	send(t, m, http.MethodPost, conditionSetsPath, `{"key": "x", "name": "X",
		"type": "resourceset"}`, http.StatusUnprocessableEntity)
	send(t, m, http.MethodPost, conditionSetsPath, `{"key": "x", "name": "X",
		"type": "resourceset", "resource_id": "folder"}`, http.StatusNotFound)
	wantFields(t, send(t, m, http.MethodPost, conditionSetsPath, `{"key": "published",
		"name": "Published", "type": "resourceset", "resource_id": "document"}`, http.StatusOK),
		`{"id": "`+ObjectID(5)+`"}`)
	wantStoredKeys(t, m, "condition_sets/drafts", "condition_sets/published",
		"condition_sets/reviewed", "resources/document")
}

// TestResourceSetOfADeletedResource checks that the fake fails the test, rather
// than guess, on a request for a resource set whose resource was deleted, and
// keeps the set.
func TestResourceSetOfADeletedResource(t *testing.T) {
	bodies := map[string]string{
		http.MethodGet: "", http.MethodPatch: `{"name": "Drafts 2"}`, http.MethodDelete: "",
	}
	for method, body := range bodies {
		t.Run(method, func(t *testing.T) {
			rec := &errorRecorder{TB: t}
			m := New(rec, Resources, ConditionSets)
			send(t, m, http.MethodPost, resourcesPath, `{"key": "document", "name": "Document",
				"actions": {}}`, http.StatusOK)
			send(t, m, http.MethodPost, conditionSetsPath, `{"key": "drafts", "name": "Drafts",
				"type": "resourceset", "resource_id": "document"}`, http.StatusOK)
			send(t, m, http.MethodDelete, resourcesPath+"/document", "", http.StatusNoContent)

			send(t, m, method, conditionSetsPath+"/drafts", body, http.StatusNotImplemented)

			wantUnconfirmed(t, rec, "names a resource set whose resource was deleted")
			wantStoredKeys(t, m, "condition_sets/drafts")
		})
	}
}

// TestConditionSetParentDelete checks that the fake fails the test, rather than
// guess, on a delete of a set that is another set's parent and keeps both, and
// deletes the parent once its child is gone.
func TestConditionSetParentDelete(t *testing.T) {
	rec := &errorRecorder{TB: t}
	m := New(rec, ConditionSets)
	send(t, m, http.MethodPost, conditionSetsPath, `{"key": "staff", "name": "Staff"}`,
		http.StatusOK)
	send(t, m, http.MethodPost, conditionSetsPath, `{"key": "admins", "name": "Admins",
		"parent_id": "`+ObjectID(1)+`"}`, http.StatusOK)

	send(t, m, http.MethodDelete, conditionSetsPath+"/staff", "", http.StatusNotImplemented)

	wantUnconfirmed(t, rec, "names the parent of the condition set admins")
	wantStoredKeys(t, m, "condition_sets/admins", "condition_sets/staff")
	send(t, m, http.MethodDelete, conditionSetsPath+"/admins", "", http.StatusNoContent)
	send(t, m, http.MethodDelete, conditionSetsPath+"/"+ObjectID(1), "", http.StatusNoContent)
	if got := rec.take(); len(got) != 0 {
		t.Errorf("test errors = %q after deleting the child first, want none", got)
	}
	wantStoredKeys(t, m)
}

func TestConditionSetRequestErrors(t *testing.T) {
	tests := []struct {
		name       string
		method     string
		body       string
		wantStatus int
	}{
		{name: "create without key", method: http.MethodPost, body: `{"name": "N"}`},
		{name: "create without name", method: http.MethodPost, body: `{"key": "k"}`},
		{
			name: "create with an unknown type", method: http.MethodPost,
			body: `{"key": "k", "name": "N", "type": "groupset"}`,
		},
		{
			name: "create with conditions not an object", method: http.MethodPost,
			body: `{"key": "k", "name": "N", "conditions": []}`,
		},
		{
			name: "create with an unknown field", method: http.MethodPost,
			body: `{"key": "k", "name": "N", "resource": "document"}`,
		},
		{
			name: "create with a parent_id not a string", method: http.MethodPost,
			body: `{"key": "k", "name": "N", "parent_id": 1}`,
		},
		{
			name: "create with an unknown parent", method: http.MethodPost,
			body:       `{"key": "k", "name": "N", "parent_id": "` + ObjectID(99) + `"}`,
			wantStatus: http.StatusNotFound,
		},
		{name: "update with an empty name", method: http.MethodPatch, body: `{"name": ""}`},
		{
			name: "update with conditions not an object", method: http.MethodPatch,
			body: `{"conditions": "subject.a == 1"}`,
		},
		{name: "update with an unknown field", method: http.MethodPatch, body: `{"key": "k2"}`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			m := New(t, ConditionSets)
			before := send(t, m, http.MethodPost, conditionSetsPath,
				`{"key": "staff", "name": "Staff", "conditions": {"allOf": []}}`, http.StatusOK)
			path := conditionSetsPath
			if tt.method == http.MethodPatch {
				path += "/staff"
			}
			wantStatus := tt.wantStatus
			if wantStatus == 0 {
				wantStatus = http.StatusUnprocessableEntity
			}

			send(t, m, tt.method, path, tt.body, wantStatus)

			wantStoredKeys(t, m, "condition_sets/staff")
			after := send(t, m, http.MethodGet, conditionSetsPath+"/staff", "", http.StatusOK)
			if !reflect.DeepEqual(after, before) {
				t.Errorf("set after the rejected request = %v, want it unchanged: %v",
					after, before)
			}
		})
	}
}

// TestConditionSetUnconfirmedBehaviour checks that the fake fails the test, rather
// than guess, on a condition set request whose effect on the API is unconfirmed.
func TestConditionSetUnconfirmedBehaviour(t *testing.T) {
	tests := []struct {
		name      string
		method    string
		body      string
		wantError string
	}{
		{
			name: "user set with a resource_id", method: http.MethodPost,
			body:      `{"key": "k", "name": "N", "resource_id": "document"}`,
			wantError: "gives a user set a resource_id",
		},
		{
			name: "parent named by key", method: http.MethodPost,
			body:      `{"key": "k", "name": "N", "parent_id": "staff"}`,
			wantError: "names the parent staff by key",
		},
		{
			name: "user set with a resource set parent", method: http.MethodPost,
			body:      `{"key": "k", "name": "N", "parent_id": "` + ObjectID(4) + `"}`,
			wantError: "a set of another type or resource",
		},
		{
			name: "resource set with a parent on another resource", method: http.MethodPost,
			body: `{"key": "k", "name": "N", "type": "resourceset", "resource_id": "folder",
				"parent_id": "` + ObjectID(4) + `"}`,
			wantError: "a set of another type or resource",
		},
		{
			name: "resource set on the built-in user resource", method: http.MethodPost,
			body:      `{"key": "k", "name": "N", "type": "resourceset", "resource_id": "__user"}`,
			wantError: "puts a resource set on the built-in __user resource",
		},
		{
			name: "parent cleared", method: http.MethodPatch, body: `{"parent_id": null}`,
			wantError: "sets parent_id to null",
		},
		{
			name: "parent is the set itself", method: http.MethodPatch,
			body:      `{"parent_id": "` + ObjectID(3) + `"}`,
			wantError: "names the set itself",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rec := &errorRecorder{TB: t}
			m := New(rec, Resources, ConditionSets)
			send(t, m, http.MethodPost, resourcesPath, `{"key": "document", "name": "D",
				"actions": {}}`, http.StatusOK)
			send(t, m, http.MethodPost, resourcesPath, `{"key": "folder", "name": "F",
				"actions": {}}`, http.StatusOK)
			before := send(t, m, http.MethodPost, conditionSetsPath,
				`{"key": "staff", "name": "Staff"}`, http.StatusOK)
			send(t, m, http.MethodPost, conditionSetsPath, `{"key": "drafts", "name": "Drafts",
				"type": "resourceset", "resource_id": "document"}`, http.StatusOK)
			path := conditionSetsPath
			if tt.method == http.MethodPatch {
				path += "/staff"
			}

			send(t, m, tt.method, path, tt.body, http.StatusNotImplemented)

			wantUnconfirmed(t, rec, tt.wantError)
			wantStoredKeys(t, m, "condition_sets/drafts", "condition_sets/staff",
				"resources/document", "resources/folder")
			after := send(t, m, http.MethodGet, conditionSetsPath+"/staff", "", http.StatusOK)
			if !reflect.DeepEqual(after, before) {
				t.Errorf("set after the refused request = %v, want it unchanged: %v", after, before)
			}
		})
	}
}
